version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "81:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
