version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "81:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  tts:
    image: ghcr.io/coqui-ai/tts-cpu
    entrypoint: /bin/bash -c "python TTS/server/server.py --model_name tts_models/en/jenny/jenny"
